apiVersion: lowops.manifests.v1
kind: BuildDefinition
metadata:
  name: island-venues-notifier
  github-repository: island-venues-notifier
  github-connection: default
  organization: island-venues
spec:
  type: GOLANG
  stages:
    - analysis
    - test
    - build
    - containerize
  golang:
    target: main.go
    buildType: bin
  containerize:
    name: island-venues-notifier
    registries:
      - docker-private
