apiVersion: lowops.manifests.v1
kind: ArtifactRegistry
metadata:
  name: static-private
  organization: island-venues
spec:
  description: Private registry for static web bundles
  enabled: true
  public: false
  type: STATIC
  permissions:
    readers:
      groups:
        - developers
      members: []
    writers:
      groups: []
      members: []
